name: app
description: A cross-platform desktop app built with Dart and Electron.
publish_to: none
environment:
  sdk: ">=2.0.0-dev <=3.0.0"
dependencies:
  js: ^0.6.0
  node_interop: ^1.0.0
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
